apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testappnode
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: testappnode=docker.io/rootchamp/testappnode
    argocd-image-updater.argoproj.io/testappnode.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/ChampAnuchit/testAppNode
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: testappnode

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
