apiVersion: apps/v1
kind: Deployment
metadata:
  name: testappnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testappnode
  template:
    metadata:
      labels:
        app: testappnode
    spec:
      containers:
        - name: testappnode
          image: ghcr.io/champanuchit/testappnode:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
